/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bouncing.presentation.Dependencia;

import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author Tulio
 */
public class ViewDependencia extends javax.swing.JFrame implements Observer{
    ModelDependencia model;
    ControllerDependencia controller;

    public void setModel(ModelDependencia model) {
        this.model = model;
        model.addObserver(this);
    }

    public void setController(ControllerDependencia controller) {
        this.controller = controller;
    }
    /**
     * Creates new form Dependencia
     */
    public ViewDependencia() {
        initComponents();
        configurar();
    }
    
    private void configurar(){
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void validarCampos(){
        if(campoNomDep.getText() !=null){
            String dependencia=campoNomDep.getText();
            //metodo para mandar la informaacion
            campoNomDep.setText(null);
        }else{
           lblNomDep.setForeground(Color.RED);
           JOptionPane.showMessageDialog(null, null, "Campos vacios", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void verificarCamposVacios(){
        if(campoNomDep.getText().isEmpty()){
            lblNomDep.setForeground(Color.RED);
        }
    }
    
    public void normalizarColor(){
        lblNomDep.setForeground(Color.BLACK);
    }
    
    public void camposVacios(){
        campoNomDep.setText(null);
    }
    
    public void validarNombre(){
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomDep = new javax.swing.JLabel();
        campoNomDep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFuncionarios = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomDep.setText("NOMBRE DEPENDENCIA:");

        campoNomDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNomDepKeyTyped(evt);
            }
        });

        tablaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaFuncionarios);

        jButton2.setText("Agregar");

        jButton3.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomDep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomDep, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(17, 17, 17)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblNomDep))
                    .addComponent(campoNomDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomDepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomDepKeyTyped
        // TODO add your handling code here:
        char car=evt.getKeyChar();
        if(Character.isLetter(car)){
            JOptionPane.showMessageDialog(null, "Nombre solo letras","TITULO",JOptionPane.ERROR_MESSAGE);
            campoNomDep.setText(null);
        }
        
    }//GEN-LAST:event_campoNomDepKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNomDep;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomDep;
    private javax.swing.JTable tablaFuncionarios;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
    }
}
